### ISSUE TITLE
Error annotations from cache post-run step

### ISSUE THREAD

**Issue by Nemo157** [actions-rust-lang/setup-rust-toolchain#20]
In https://github.com/Nullus157/.github/actions/runs/5048663303 I'm seeing a bunch of error annotations:

> Error: ENOENT: no such file or directory, opendir '/home/runner/.cargo/registry/index'

stepping into one of the jobs these are coming from the post-run action when it goes to clean the registry before caching, presumably because I have no dependencies so no registry data is downloaded https://github.com/Nullus157/.github/actions/runs/5048663303/jobs/9057129303#step:7:31

**Comment by jonasbb** [comment]
Thanks for the information. Indeed, there is a problem with https://github.com/Swatinem/rust-cache. `rust-cache` is the only part of this action with post-run steps. This minimal action with a Rust project without dependencies is enough to trigger the error:
```yaml
- uses: actions/checkout@v3
- uses: Swatinem/rust-cache@v2
- run: cargo check --all
```

You can disable the cache action by setting the `cache` input value to `false`:
```yaml
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
```
For a proper fix, you should raise the issue again in the `rust-cache` repository.
