### ISSUE TITLE
gcc-mingw-w64-x86-64 required

### ISSUE THREAD

**Issue by Propfend** [actions-rust-lang/setup-rust-toolchain#50]
im using the following block of code for including the `x86_64-pc-windows-gnu` toolchain into my workflow state:

```yaml
strategy:
  matrix:
    include:
      - rust_target: x86_64-unknown-linux-gnu 
        artifact_name: paddler-bin-linux-amd64

      - rust_target: x86_64-pc-windows-gnu
        artifact_name: paddler-bin-windows-amd64.exe

steps:
  - name: checkout code
    uses: actions/checkout@v4

  - name: Set up Rust
    uses: actions-rust-lang/setup-rust-toolchain@v1
    with:
      toolchain: stable
      target: ${{ matrix.rust_target }}
```

but still receiving the error 

```bash
gcc-mingw-w64-x86-64 not installed
```

it just works when i manually install the `gcc-mingw-w64-x86-64` toolchain with:

```yaml
- name: Install mingw for Windows cross-compilation
  if: matrix.rust_target == 'x86_64-pc-windows-gnu'
  run: sudo apt-get install -y gcc-mingw-w64-x86-64
```

How to do to include it?
